spring:
  datasource:
    #    url: jdbc:h2:file:D:/Users/0105690/Desktop/SpringBoot/RtnNote/testdb
    url: jdbc:h2:mem:testdb;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2